# Path
data:
  raw_dir: "data/ru-fr_interference/2"
  metadata_file: "metadata_RUFR.csv"
  corr_file: "RUFRcorr.csv"
  phoneme_tier: 2

# Output
out_dir: "outputs"
analysis_dir: "outputs/analysis"
neural_norm_dir: "outputs/neural_norm"

# Acoustic extraction
acoustic:
  n_formants: 5

# Whisper extraction
whisper:
  model: "openai/whisper-large-v3"
  layers: [8, 28]
  device: "cuda"

# XLS-R extraction
xlsr:
  model: "facebook/wav2vec2-large-xlsr-53"
  layers: [4, 12, 20]
  device: "cuda"

# Normalisation & dimensionality reduction
normalise:
  n_pca_clust: 50
  n_pca_lme: 5
  n_umap_neighbors: 15
  umap_min_dist: 0.1